export const BACKEND_URL = 'http://localhost:8000';
export const accessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlck9uZTFARmx1eC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjQxMTg4OSwiZXhwIjoxNzQyNDk4Mjg5fQ.iilmBJEhhWZUIuBY1x4IWMtfwdsWcjEA97Al1dA_YEc";
