export const BACKEND_URL = 'http://localhost:8000';
export const accessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlck9uZTFARmx1eC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjM2MDIyNCwiZXhwIjoxNzQyMzYzODI0fQ.BqXzjIba93wsvwEyoS11Z_fLrBBIeBjINdTItNFtBOA";
